--
-- Tests for return correct error from qe when create extension error
-- The issue: https://github.com/greenplum-db/gpdb/issues/11304
--
--start_ignore
drop extension if exists gp_debug_numsegments;
NOTICE:  extension "gp_debug_numsegments" does not exist, skipping
create extension if not exists gp_inject_fault;
--end_ignore
select gp_inject_fault('create_function_fail', 'error', 2);
 gp_inject_fault 
-----------------
 Success:
(1 row)

create extension gp_debug_numsegments;
ERROR:  fault triggered, fault name:'create_function_fail' fault type:'error'  (seg0 192.168.106.132:7002 pid=153052)
select gp_inject_fault('create_function_fail', 'reset', 2);
 gp_inject_fault 
-----------------
 Success:
(1 row)

